name = "member-area-template"
main = ".open-next/worker.js"
compatibility_date = "2026-08-17"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "member-area-template"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "member-area-template-d1"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "./drizzle"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "member-area-template-storage"
